# Generated by Django 3.0.6 on 2021-04-19 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livestream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_id', models.CharField(max_length=255, unique=True)),
                ('video_APIKey', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('R', 'Run'), ('Y', 'Yoga'), ('HC', 'Home cardio'), ('T', 'Tennis'), ('S', 'Swimming'), ('B', 'Basketball'), ('C', 'Cycling'), ('J', 'Jump rope'), ('H', 'Hiking'), ('O', 'Other')], default='O', max_length=2)),
            ],
        ),
    ]
