describe('Forgot Password', () => {
  it('User successfully updates password', () => {
    cy.viewport('iphone-7')
	  cy.visit('http://localhost:19006/')
    cy.get('button[name="forgot"')
          .click()
    cy.get('input[name="username"')
          .type('ayushigupta')
          .should('have.value', 'ayushigupta')
    cy.get('input[name="password"')
          .type('newpass')
          .should('have.value', 'newpass')
    cy.get('input[name="confirm"')
          .type('newpass')
          .should('have.value', 'newpass')
    cy.get('button[name="enter"')
                .click()
    cy.url().should('include', '/login')
  })
})
