describe('Delete Profile', () => {
  it('Deletes the users profile and takes them to the login screen', () => {
    cy.viewport('iphone-7')
	  cy.visit('http://localhost:19006/')
    cy.get('input[name="username"')
          .type('ayushigupta')
          .should('have.value', 'ayushigupta')
    cy.get('input[name="password"')
          .type('AYUSHI')
          .should('have.value', 'AYUSHI')
    cy.get('button[name="enter"')
          .click()
    cy.get('button[name="profie"')
                .click()
    cy.get('button[name="delete"')
                      .click()
    cy.url().should('include', '/login')
  })
})

describe('Update Profile', () => {
  it('Takes the user to the update password screen', () => {
    cy.viewport('iphone-7')
	  cy.visit('http://localhost:19006/')
    cy.get('input[name="username"')
          .type('ayushigupta')
          .should('have.value', 'ayushigupta')
    cy.get('input[name="password"')
          .type('AYUSHI')
          .should('have.value', 'AYUSHI')
    cy.get('button[name="enter"')
          .click()
    cy.get('button[name="profie"')
                .click()
    cy.get('button[name="update"')
                      .click()
    cy.url().should('include', '/update')
  })
})
